account/urls.py
from django.urls import path
from . import views


app_name = 'account'

urlpatterns = [
    path('login/', views.login_view, name='login_view'),
    path('register/', views.register, name='register'),
    path('logout_view/', views.logout_view, name='logout_view'),
]

job_order/urls.py
from django.urls import path

from . import views

app_name = 'job_order'


urlpatterns = [
 path('', views.index, name='index'),
 path('my_main/', views.my_main, name='my_main'),
 path('locations/', views.locations, name='locations'),
 path('locations/<int:location_id>/', views.location, name='location'),
 path('processes/<int:process_id>/', views.process, name='process'),
 path('add_equipment/<int:process_id>/', views.add_equipment, name='add_equipment'),
 path('add_parts/<int:equipment_id>/', views.add_parts, name='add_parts'),
 path('equipments/<int:equipment_id>/', views.equipment, name='equipment'),
 path('parts/', views.parts, name='parts'),
 path('parts/<int:part_id>/', views.part, name='part'),
 path('equipments/', views.equipments, name='equipments'),
 path('jo_lists/', views.jo_lists, name='jo_lists'),
 path('jo_lists/<int:jo_list_id>/', views.jo_list, name='jo_list'),
 path('create_jo/', views.create_jo, name='create_jo'),
 path('edit_jo/<int:job_order_id>/', views.edit_jo, name='edit_jo'),
 path('edit_equipment/<int:equipment_id>/', views.edit_equipment, name='edit_equipment'),
 path('edit_parts/<int:part_id>/', views.edit_parts, name='edit_parts'),
 path('details/<int:detail_id>/', views.detail, name='detail'),
 path('file_pdf/<int:file_id>/', views.generate_Filepdf, name='generate_Filepdf'),
 path('pdf_report/', views.pdf_report, name='pdf_report'),
 path('export_jo_to_excel/', views.jo_excel, name='jo_excel'),
 path('time_diff/', views.time_diff, name='time_diff'),
 path('starter/', views.starter, name='starter'),
 path('close_jo', views.close_jo, name='close_jo'),
 path('disabled_register/', views.disabled_register, name='disabled_register'),
 path('supervisor_list', views.supervisor_list, name='supervisor_list'),
]

joplus/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    #path('users/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls')),
    path('', include('job_order.urls')),
    #path("__debug__/", include("debug_toolbar.urls")),
]

#urlpatterns += static(settings.MEDIA_URL, docoment_root=settings.MEDIA_ROOT)
#urlpatterns += static(settings.STATIC_URL, docoment_root=settings.STATIC_ROOT)

job_order/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime, timezone
# Create your models here.
class Location(models.Model):
 location = models.CharField(max_length=64)

 def __str__(self):
  return f'{self.location}'


class Process(models.Model):
 process = models.CharField(max_length=64)
 location = models.ForeignKey(Location, on_delete=models.CASCADE, related_name='processes')

 def __str__(self):
  return f'{self.process}'


class Equipment(models.Model):
 equipment = models.CharField(max_length=64)
 process = models.ForeignKey(Process, on_delete=models.CASCADE, related_name='machines')

 def __str__(self):
  return f'{self.equipment}'


class EquipmentSpecs(models.Model):
 specs = models.TextField() 
 equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE, related_name='specifications')

 def __str__(self):
  return f'{self.specs}'


class EquipmentParts(models.Model):
 parts = models.CharField(max_length=64)
 equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE, related_name='spare_parts')

 def __str__(self):
  return f'{self.parts}' 


class Requestor(models.Model):
 name = models.CharField(max_length=64)

 def __str__(self):
  return f"{self.name}"


class Issued_To(models.Model):
 jo_issued_to = models.CharField(max_length=64)

 def __str__(self):
  return f"{self.jo_issued_to}"


class Approver(models.Model):
 approver = models.CharField(max_length=64)

 def __str__(self):
  return f"{self.approver}"


class Service_Type(models.Model):
 service = models.CharField(max_length=64)

 def __str__(self):
  return f"{self.service}"


class Department(models.Model):
 department = models.CharField(max_length=64)

 def __str__(self):
  return f"{self.department}"


class Job_Order(models.Model):
 date = models.DateTimeField(auto_now_add=True)
 issued_to = models.ForeignKey(Issued_To, on_delete=models.CASCADE, related_name='assigned_to')
 location = models.ForeignKey(Location, on_delete=models.CASCADE, related_name='area_located')
 process = models.ForeignKey(Process, on_delete=models.CASCADE, related_name='systems')
 equipment = models.ForeignKey(Equipment, on_delete=models.CASCADE, related_name='machine_unit')
 parts = models.ForeignKey(EquipmentParts, on_delete=models.CASCADE, related_name='parts_lists')
 service_type = models.ForeignKey(Service_Type, on_delete=models.CASCADE, related_name='job_type')
 requestor = models.ForeignKey(Requestor, on_delete=models.CASCADE, related_name='requested_by')
 complaint = models.TextField()
 department = models.ForeignKey(Department, on_delete=models.CASCADE, related_name='dept')
 approver = models.ForeignKey(Approver, on_delete=models.CASCADE, related_name='approve_by')
 status = models.BooleanField(default=True)
 lead_times = models.IntegerField(default=0)
 #remove function owner = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)


 @property
 def jo_issued_to(self):
  return self.issued_to.jo_issued_to

 def __str__(self):
  return f'{self.complaint[0:50]}...'

 
 def save(self, *args, **kwargs):
  super().save(*args, **kwargs)

job_order/forms.py
from django import forms
from .models import Equipment, EquipmentParts, Job_Order

#Create forms
class EquipmentForm(forms.ModelForm):
 class Meta:
  model = Equipment
  fields = ['equipment']
  labels = {'equipment': 'Equipment'}


class PartsForm(forms.ModelForm):
 class Meta:
  model = EquipmentParts
  fields = ['parts']
  labels = {'parts': 'Parts'}


class JobOrderForm(forms.ModelForm):
 class Meta:
  model = Job_Order
  fields = [
    'issued_to', 'location', 'process', 'equipment', 'parts', 'service_type', 'requestor',
    'complaint', 'department', 'approver',  'status'
   ]
  labels = {
    'issued_to': 'Issued to: ', 'location': 'Location: ', 'process': 'Process: ', 
    'equipment': 'Equipment: ', 'parts': 'Parts: ', 'service_type': 'Service Type', 
    'requestor': 'Requestor: ', 'complaint': 'Complaint', 'department': 'Department',
    'approver': 'Approver: ', 'status': 'Open: '
  }


class CloseForm(forms.ModelForm):
 class Meta:
  model = Job_Order
  fields = ['status']
  labels = {'status': 'Uncheck to closed:'}
  

job_order/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from .models import (Location, Process, Equipment, EquipmentParts, Job_Order)
from .forms import (EquipmentForm, PartsForm, JobOrderForm, CloseForm)
import pandas as pd
from datetime import datetime, timezone
from django.db.models import Prefetch

from django.http import FileResponse
import io
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import letter


#Create your views here.

def index(request):
    return render(request, 'job_order/index.html')


@login_required
def my_main(request):
    return render(request, 'job_order/my_main.html')


@login_required
def locations(request):
    locations = Location.objects.all()
    context = {'locations': locations}
    return render(request, 'job_order/locations.html', context)


def location(request, location_id):
    location = Location.objects.get(id=location_id)
    processes = location.processes.all()
    context = {'processes': processes, 'location': location}
    return render(request, 'job_order/location.html', context)


def process(request, process_id):
    process = Process.objects.get(id=process_id)
    machines = process.machines.all()
    context = {'process': process, 'machines': machines}
    return render(request, 'job_order/process.html', context)


@login_required
def add_equipment(request, process_id):
    """Add equipment to a particular process"""
    process = Process.objects.get(id=process_id)
    if request.method != 'POST':
    #No data submitted, create a blank form
        form = EquipmentForm()
    else:
    #POST data submitted, process data
        form = EquipmentForm(data=request.POST)
        if form.is_valid():
            add_equipment = form.save(commit=False)
            add_equipment.process = process
            add_equipment.save()
            return redirect('job_order:process', process_id=process_id)

    #Display blank or invalid form
    context = {'form': form, 'process': process}
    return render(request, 'job_order/add_equipment.html', context)


@login_required
def add_parts(request, equipment_id):
    """Add parts to the equipment"""
    #No data submitted, create blank form
    equipment = Equipment.objects.get(id=equipment_id) 
    if request.method != 'POST':
        form = PartsForm()
    else:
        #POST data submitted, process data
        form = PartsForm(data=request.POST)
    if form.is_valid():
        add_parts = form.save(commit=False)
        add_parts.equipment = equipment
        add_parts.save()
        return redirect('job_order:equipment', equipment_id=equipment_id)

    #Display blank or invalid form
    context = {'equipment': equipment, 'form': form}
    return render(request, 'job_order/add_parts.html', context)


def parts(request):
    parts = EquipmentParts.objects.all()
    context = {'parts': parts}
    return render(request, 'job_order/parts.html', context)


def part(request, part_id):
    part = EquipmentParts.objects.get(id=part_id)
    parts_lists = part.parts_lists.all()
    context = {'part': part, 'parts_lists': parts_lists}
    return render(request, 'job_order/part.html', context)


def equipments(request):
    equipments = Equipment.objects.all()
    context = {'equipments': equipments}
    return render(request, 'job_order/equipments.html', context) 


def equipment(request, equipment_id):
    equipment = Equipment.objects.get(id=equipment_id)
    job_order = equipment.machine_unit.all()
    specifications = equipment.specifications.all()
    spare_parts = equipment.spare_parts.all()
    context = {
        'specifications': specifications, 
        'spare_parts': spare_parts, 
        'equipment': equipment, 
        'job_order': job_order
        }
    return render(request, 'job_order/equipment.html', context)


def jo_lists(request):
    jo_lists = Job_Order.objects.filter(status=True)
    for jo_list in jo_lists:
        jo_list.date = jo_list.date.strftime("%m/%d/%Y")
    
    close_lists = Job_Order.objects.filter(status=False)
    for close_list in close_lists:
        close_list.date = close_list.date.strftime("%m/%d/%Y")
    context = {'jo_lists': jo_lists, 'close_lists': close_lists}
    return render(request, 'job_order/jo_lists.html', context)


def supervisor_list(request):
    #jo_lists = Job_Order.objects.filter(owner=request.user)
    jo_lists = Job_Order.objects.filter(status=True)
    for jo_list in jo_lists:
        jo_list.date = jo_list.date.strftime("%m/%d/%Y")
    
    close_lists = Job_Order.objects.filter(status=False)
    for close_list in close_lists:
        close_list.date = close_list.date.strftime("%m/%d/%Y")
    
    context = {'jo_lists': jo_lists, 'close_lists': close_lists}
    return render(request, 'job_order/supervisor_list.html', context)


@login_required
def create_jo(request):
    """Create job order"""
    #No data submitted, create a blank form
    if request.method != 'POST':
        form = JobOrderForm()
    else:
    #POST data submitted, process data
        form = JobOrderForm(data=request.POST) 
    if form.is_valid():
        form.save()
        return redirect('job_order:supervisor_list') 

    #Display blank or invalid form
    context = {'form': form}
    return render(request, 'job_order/create_jo.html', context)


@login_required
def edit_jo(request, job_order_id):
    """Edit existing job order"""
    job_order = Job_Order.objects.get(id=job_order_id) 

    if request.method != 'POST':
        #Initial request: prefill form with current jo entry
        form = JobOrderForm(instance=job_order)
    else:
        #POST data submitted, process data
        form = JobOrderForm(instance=job_order, data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('job_order:jo_lists') 

    context = {'job_order': job_order, 'form': form}
    return render(request, 'job_order/edit_jo.html', context)


def jo_list(request, jo_list_id):
    jo_list = Job_Order.objects.get(id=jo_list_id)
    if jo_list.date:
        jo_list.date = jo_list.date.strftime("%m/%d/%Y")
    context = {'jo_list': jo_list}
    return render(request, 'job_order/jo_list.html', context) 


@login_required
def edit_equipment(request, equipment_id):
    """Edit equipment"""
    equipment = Equipment.objects.get(id=equipment_id)
    process = equipment.process

    if request.method != 'POST':
        #Initial request, pre-fill the form with the current data
        form = EquipmentForm(instance=equipment)
    else:
        #POST data submitted, process data
        form = EquipmentForm(instance=equipment, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('job_order:equipment', equipment_id=equipment.id)
    
    context = {'form': form, 'equipment': equipment, 'process': process}
    return render(request, 'job_order/edit_equipment.html', context)


@login_required
def edit_parts(request, part_id):
    """Edit parts"""
    part = EquipmentParts.objects.get(id=part_id)
    equipment = part.equipment

    if request.method != 'POST':
        #Initial request, pre-fill the form with current data...
        form = PartsForm(instance=part)
    else:
        #POST data submitted, process data
        form = PartsForm(instance=part, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('job_order:part', part_id=part.id)
    
    context = {'part': part, 'equipment': equipment, 'form': form}
    return render(request, 'job_order/edit_parts.html', context)


@login_required
def detail(request, detail_id):
    detail = Job_Order.objects.get(id=detail_id)
    context = {'detail': detail}
    return render(request, 'job_order/details.html', context)


@login_required
def pdf_report(request):
    pdf_reports = Job_Order.objects.all()
    for pdf_report in pdf_reports:
        pdf_report.date = pdf_report.date.strftime("%m/%d/%Y")
    context = {'pdf_reports': pdf_reports}
    return render(request, 'job_order/pdf_report.html', context)


@login_required
def generate_Filepdf(request, file_id):
    
    from io import BytesIO
    from PIL import Image

    buffer = BytesIO()
    p = canvas.Canvas(buffer)
    
    # Create a PDF document
    jo = Job_Order.objects.get(id=file_id)
    
    # define a large font
    p.setFont("Helvetica", 20)
    p.drawString(270, 800, "JOB ORDER REQUEST - CES")
 
    p.rect(x=230, y=780, width=355, height=50, stroke=1, fill=0)
    p.rect(x=15, y=780, width=215, height=50, stroke=1, fill=0) 
 
    y = 775
    p.setFont("Helvetica", 12)
    p.drawString(20, y - 20, f"Job Order ID: {jo.id}")
    date_convert = jo.date.strftime("%m/%d/%Y")
    p.drawString(350, y - 20, f"Date: {date_convert}")
    p.drawString(20, y - 40, f"Issued To: {jo.issued_to}")
    p.drawString(350, y - 40, f"Dept.: {jo.department}")
    p.drawString(20, y - 60, f"Location: {jo.location}")
    p.drawString(350, y - 60, f"System: {jo.process}")
    p.drawString(20, y - 80, f"Equipment: {jo.equipment}")
    p.drawString(350, y - 80, f"Part name: {jo.parts}")
    p.drawString(20, y - 100, f"Complaint:")
    p.rect(x=15, y=600, width=570, height=70, stroke=1, fill=0)
    p.drawString(25, y - 120, f"{jo.complaint}")
    p.drawString(20, y - 190, f"Service type: {jo.service_type}")
    p.drawString(350, y - 190, f"Received by (PMD/EID):")
    p.drawString(20, y - 230, f"Requested by: {jo.requestor}")
    p.drawString(350, y - 230, f"Opt. Asst./Planner/S'visor:______________")
    p.drawString(20, y - 265, f"Approved by: {jo.approver}")
    p.drawString(350, y - 265, f"Approved by (Dept. Head):_____________")
    x_start = 0
    y_start = 0
    #image = Image.open('abi_logo.jpeg')
    p.drawImage('abi_logo.png', 25, 782, width=195, height=45)
    p.line(x1=20, y1=500, x2=570, y2=500)
    p.setFont("Helvetica", 8)

job_order/templates/job_order/add_equipment.html
{%extends 'job_order/layout.html'%}

{% block body %}
<h2>Welcome to Job Order Plus</h2>
<p><a href="{% url 'job_order:process' process.id %}">{{ process }}</a></p>

<form action="{% url 'job_order:add_equipment' process.id %}" method="post">
 {% csrf_token %}
 {{ form.as_p }}
 <button name="submit">Add equipment</button>
</form>
{% endblock %}

job_order/templates/job_order/close_jo.html
{%extends 'job_order/layout.html'%}
{% load bootstrap4 %}
{% block page_header %}
    <h2>Close Job Order</h2>
{% endblock page_header %}
{% block body %}
      <style>
         table, th, td {
         border: 1px solid black;
         border-collapse: collapse;
         }
      </style>
      <table style="width:100%">
         <tr>
            <th>JO ID</th>
            <th>Date</th>
            <th>Equipment</th>
            <th>Requestor</th>
            <th>Complaint</th>
            <th>Open</th>
         </tr>
   {% for close in jo_close %}
         <tr>
            <td>{{ close.id }}</td>
            <td>{{ close.date }}</td>
            <td>{{ close.equipment }}</td>
            <td>{{ close.requestor }}</td>
            <td>{{ close.complaint }}</td>
            <td>{{ close.status }}</td>
         </tr>
      
  {% empty %}
     <li>No data</li>
  {% endfor %}
      </table>
<p><a href="{% url 'job_order:my_main' %}">Back to main menu</a></p>
{% endblock %}

job_order/templates/job_order/create_jo.html
{%extends 'job_order/layout.html'%}
{% load bootstrap4 %}
{% block page_header %}
    <h2>Create Job Order</h2>
{% endblock page_header %}
{% block body %}
<form action="{% url 'job_order:create_jo' %}" method="post">
 {% csrf_token %}
 {% bootstrap_form form %}
 {% buttons %}
    <button name="submit" class="btn btn-primary"> Submit</button>
 {% endbuttons %}
 <input type="hidden" name="next"
 value="{% url 'job_order:index' %}" />
</form>
{% endblock %}

job_order/templates/job_order/edit_jo.html
{%extends 'job_order/layout.html'%}
{% load bootstrap4 %}
{% block page_header %}
    <h2>Edit Job Order</h2>
{% endblock page_header %}
{% block body %}
<form action="{% url 'job_order:edit_jo' job_order.id %}" method="post">
 {% csrf_token %}
 {% bootstrap_form form %}
 {% buttons %}
    <button name="submit" class="btn btn-primary"> Save changes</button>
 {% endbuttons %}
 <input type="hidden" name="next"
 value="{% url 'job_order:index' %}" />
</form>
{% endblock %}

job_order/templates/job_order/equipments.html
{%extends 'job_order/layout.html'%}

{% block page_header %}
    <h1>Equiments</h1>
{% endblock page_header %}

{% block body %}
{% for equipment in equipments %}
    <li>{{ equipment }}</li>
{% empty %}
    <li>No data added</li>
{% endfor %}
    <p><a href="{% url 'job_order:my_main' %}">Back to main menu</a></p>
{% endblock %}

job_order/templates/job_order/jo_list.html
{%extends 'job_order/layout.html'%}

{% block body %}
<h3>Complaint: {{ jo_list }}</h3>
<p><a href="{% url 'job_order:edit_jo' jo_list.id %}">Edit Job Order</a></p>
<style>
    table, th, td {
      border: 1px solid black;
      border-collapse: collapse;
    }
</style>

<table style="width:100%">
    <tr>
      <th>Parameters</th>
      <th>Data</th> 
    </tr>
    <tr>
      <td>Job Order ID</td>
      <td>{{ jo_list.id }}</td>
    </tr>
    <tr>
      <td>Date</td>
      <td>{{ jo_list.date }}</td>
    </tr>
    <tr>
      <td>Issued to</td>
      <td>{{ jo_list.issued_to }}</td>
    </tr>
    <tr>
        <td>Location</td>
        <td>{{ jo_list.location }}</td>
    </tr>
    <tr>
        <td>Process</td>
        <td>{{ jo_list.process }}</td>
    </tr>
    <tr>
        <td>Equipment</td>
        <td>{{ jo_list.equipment }}</td>
    </tr>
    <tr>
        <td>Parts</td>
        <td>{{ jo_list.parts }}</td>
    </tr>
    <tr>
        <td>Service Type</td>
        <td>{{ jo_list.service_type }}</td>
    </tr>
    <tr>
        <td>Requestor</td>
        <td>{{ jo_list.requestor }}</td>
    </tr>
    <tr>
        <td>Comlaint</td>
        <td>{{ jo_list.complaint }}</td>
    </tr>
    <tr>
        <td>Department</td>
        <td>{{ jo_list.department }}</td>
    </tr>
    <tr>
        <td>Approver</td>
        <td>{{ jo_list.approver }}</td>
    </tr>
    <tr>
        <td>Open</td>
        <td>{{ jo_list.status }}</td>
    </tr>
  </table>

  <p></p>
  {% endblock %}

job_order/templates/job_order/jo_lists.html
{%extends 'job_order/layout.html'%}

{% block body %}
<h3>Job Order List</h3>
      <style>
         table, th, td {
         border: 1px solid black;
         border-collapse: collapse;
         }
      </style>
      <table style="width:100%">
         <tr>
            <th>Details</th>
            <th>JO ID</th>
            <th>Date</th>
            <th>Equipment</th>
            <th>Requestor</th>
            <th>Complaint</th>
         </tr>
   {% for jo_list in jo_lists %}
         <tr>
            <td>
            <a href="{% url 'job_order:jo_list' jo_list.id %}">Click</a>
            </td>
            <td>{{ jo_list.id }}</td>
            <td>{{ jo_list.date }}</td>
            <td>{{ jo_list.equipment }}</td>
            <td>{{ jo_list.requestor }}</td>
            <td>{{ jo_list.complaint }}</td>
         </tr>
      
  {% empty %}
     <li>No data</li>
  {% endfor %}
      </table>
<p><a href="{% url 'job_order:my_main' %}">Back to main menu</a></p>
{% endblock %}

job_order/templates/job_order/layout.html
{% load bootstrap4 %}
{% load static %}
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1,
shrink-to-fit=no">
<title>JO+</title>
{% bootstrap_css %}
{% bootstrap_javascript jquery='full' %}
</head>
  <body>
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

	  <a class="navbar-brand" href="{% url 'job_order:index' %}">
		Job Order</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse"
		data-target="#navbarCollapse" aria-controls="navbarCollapse"
		aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span></button>

		<div class="collapse navbar-collapse" id="navbarCollapse">
		  <ul class="navbar-nav mr-auto">
		   <li class="nav-item">
			<a class="nav-link" href="{% url 'job_order:locations' %}">
			Location</a></li>
		   <li class="nav-item">
	     	<a class="nav-link" href="{% url 'job_order:create_jo' %}">
			Create JO</a></li>
		   <li class="nav-item">
			<a class="nav-link" href="{% url 'job_order:jo_lists' %}">
            JO Details</a></li>
		   <li class="nav-item">
			<a class="nav-link" href="{% url 'job_order:pdf_report' %}">
			Download</a></li>
			<li class="nav-item">
			<a class="nav-link" href="{% url 'job_order:time_diff' %}">
			Timeframe</a></li>
			<li class="nav-item">
			<a class="nav-link" href="{% url 'job_order:starter' %}">
			Charts</a></li>
			<li class="nav-item">
			<a class="nav-link" href="{% url 'job_order:close_jo' %}">
			JO Closed</a></li>
		   </ul>

			<ul class="navbar-nav ml-auto">
			 {% if user.is_authenticated %}
			 <li class="nav-item">
			 <span class="navbar-text">Hello, {{ user.username }}.</span>
			 </li>
			 <li class="nav-item">
			 <a class="nav-link" href="{% url 'account:logout_view' %}">Log out</a>
			 </li>
			 {% else %}
			 <li class="nav-item">
			 <a class="nav-link" href="{% url 'account:register' %}">Register</a>
			 </li>
			 <li class="nav-item">
			 <a class="nav-link" href="{% url 'account:login_view' %}">Log in</a></li>
			 {% endif %}
			</ul>
		</div>
	</nav>

	<main role="main" class="container">
	 <div class="pb-2 mb-2 border-bottom">
	  {% block page_header %}{% endblock page_header %}
	 </div>
     <div>
	  {% block body %}{% endblock %}
	 </div>
	</main>
  </body>
 </html>

job_order/templates/job_order/location.html
{%extends 'job_order/layout.html'%}

{% block body %}
<h3>Location ID: {{ location.id }}</h3>
<h3>Location: {{ location }}</h3>
 <ul>
  {% for process in processes %}
     <li><a href="{% url 'job_order:process' process.id %}">{{ process }}</a></li>
  {% empty %}
     <li>No data</li>
  {% endfor %}
 </ul>

<p><a href="{% url 'job_order:my_main' %}">Back to main menu</a></p>
{% endblock %}

job_order/templates/job_order/parts.html
{%extends 'job_order/layout.html'%}

{% block body %}
<h3>Equipment parts</h3>
 <ul>
  {% for parts in parts %}
     <li>{{ parts }}</li>
  {% empty %}
     <li>No data</li>
  {% endfor %}
 </ul>
<p><a href="{% url 'job_order:my_main' %}">Back to main menu</a></p>
{% endblock %}

job_order/templates/job_order/pdf_report.html
{%extends 'job_order/layout.html'%}

{% block body %}
<h3>Job Order List</h3>
      <style>
         table, th, td {
         border: 1px solid black;
         border-collapse: collapse;
         }
      </style>
      <table style="width:100%">
         <tr>
            <th>Details</th>
            <th>JO ID</th>
            <th>Date</th>
            <th>Equipment</th>
            <th>Requestor</th>
            <th>Complaint</th>
            <th>Open</th>
         </tr>
   {% for pdf_report in pdf_reports %}
         <tr>
            <td>
            <a href="{% url 'job_order:generate_Filepdf' pdf_report.id %}">Download pdf</a>
            </td>
            <td>{{ pdf_report.id }}</td>
            <td>{{ pdf_report.date }}</td>
            <td>{{ pdf_report.equipment }}</td>
            <td>{{ pdf_report.requestor }}</td>
            <td>{{ pdf_report.complaint }}</td>
            <td>{{ pdf_report.status }}</td>
         </tr>
      
  {% empty %}
     <li>No data</li>
  {% endfor %}
      </table>
<p><a href="{% url 'job_order:my_main' %}">Back to main menu</a></p>
<p><a href="{% url 'job_order:jo_excel' %}">Download file in excel format</a></p>
{% endblock %}

job_order/templates/job_order/process.html
{%extends 'job_order/layout.html'%}

{% block body %}
<h3>Process ID: {{ process.id }}</h3>
<h3>Process: {{ process }}</h3>
 <ul>
  {% for equipment in machines %}
     <li><a href="{% url 'job_order:edit_equipment' equipment.id %}">Edit.....</a>
      <a href="{% url 'job_order:equipment' equipment.id %}">{{   equipment }}</a></li>
  {% empty %}
     <li>No data</li>
  {% endfor %}
 </ul>
<p><a href="{% url 'job_order:add_equipment' process.id %}">Add equipment</a></p>
<p><a href="{% url 'job_order:my_main' %}">Back to main menu</a></p>
{% endblock %}